<?php include_once 'src/templates/header.phtml'; ?>

<form class="w-50 mx-auto my-5" action="panel/canchas/actualizar/<?= $id ?>" method="POST" enctype="multipart/form-data">
<a href="/canchas/panel/canchas" class="btn btn-outline-primary">Volver al listado</a>
    <div class="mb-3">
        <label for="cesped" class="form-label">Tipo Cesped</label>
        <input type="text" class="form-control" name="cesped" id="cesped" placeholder="Escribe un tipo de cesped">
    </div>
    <div class="mb-3">
        <label for="precio" class="form-label">Precio</label>
        <input type="number" class="form-control" name="precio" id="precio" placeholder="10000">
    </div>

    <div class="mb-3">
        <label for="techada" class="form-label">Esta Techada</label>
        <select name="techada" id="techada">
            <option value="true">Si</option>
            <option value="false">No </option>
        </select>
    </div>

    <button type="submit" class="btn btn-warning w-100">Editar Cancha</button>
</form>

<?php include_once 'src/templates/footer.phtml'; ?>